// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD5g5wzHfSN_gIycP4n_aeXcq2NiQXoUs',
    appId: '1:222500882225:web:5c118d30f75cbed7431210',
    messagingSenderId: '222500882225',
    projectId: 'zuhairy-rent-it-project',
    authDomain: 'zuhairy-rent-it-project.firebaseapp.com',
    storageBucket: 'zuhairy-rent-it-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyZwX8hD1naFl6L-S-BSOmxBbJpeoI6b8',
    appId: '1:222500882225:android:c1a6db559ab18044431210',
    messagingSenderId: '222500882225',
    projectId: 'zuhairy-rent-it-project',
    storageBucket: 'zuhairy-rent-it-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT0OqXJzZ4ngNFy44QXrdn9-g2YrAerTM',
    appId: '1:222500882225:ios:faf6beb478d03994431210',
    messagingSenderId: '222500882225',
    projectId: 'zuhairy-rent-it-project',
    storageBucket: 'zuhairy-rent-it-project.appspot.com',
    iosBundleId: 'com.example.rentIt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT0OqXJzZ4ngNFy44QXrdn9-g2YrAerTM',
    appId: '1:222500882225:ios:751cddd136714469431210',
    messagingSenderId: '222500882225',
    projectId: 'zuhairy-rent-it-project',
    storageBucket: 'zuhairy-rent-it-project.appspot.com',
    iosBundleId: 'com.example.rentIt.RunnerTests',
  );
}
